const stub = [
    {
      "login": "dan",
      "id": 219,
      "avatar_url": "https://avatars.githubusercontent.com/u/219?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dan",
      "html_url": "https://github.com/dan",
      "followers_url": "https://api.github.com/users/dan/followers",
      "following_url": "https://api.github.com/users/dan/following{/other_user}",
      "gists_url": "https://api.github.com/users/dan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dan/subscriptions",
      "organizations_url": "https://api.github.com/users/dan/orgs",
      "repos_url": "https://api.github.com/users/dan/repos",
      "events_url": "https://api.github.com/users/dan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dan/received_events",
      "type": "User",
      "site_admin": false,
      "score": 111.750275
    },
    {
      "login": "dhrrgn",
      "id": 149921,
      "avatar_url": "https://avatars.githubusercontent.com/u/149921?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dhrrgn",
      "html_url": "https://github.com/dhrrgn",
      "followers_url": "https://api.github.com/users/dhrrgn/followers",
      "following_url": "https://api.github.com/users/dhrrgn/following{/other_user}",
      "gists_url": "https://api.github.com/users/dhrrgn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dhrrgn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dhrrgn/subscriptions",
      "organizations_url": "https://api.github.com/users/dhrrgn/orgs",
      "repos_url": "https://api.github.com/users/dhrrgn/repos",
      "events_url": "https://api.github.com/users/dhrrgn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dhrrgn/received_events",
      "type": "User",
      "site_admin": false,
      "score": 28.468105
    },
    {
      "login": "danlucraft",
      "id": 6118,
      "avatar_url": "https://avatars.githubusercontent.com/u/6118?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danlucraft",
      "html_url": "https://github.com/danlucraft",
      "followers_url": "https://api.github.com/users/danlucraft/followers",
      "following_url": "https://api.github.com/users/danlucraft/following{/other_user}",
      "gists_url": "https://api.github.com/users/danlucraft/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danlucraft/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danlucraft/subscriptions",
      "organizations_url": "https://api.github.com/users/danlucraft/orgs",
      "repos_url": "https://api.github.com/users/danlucraft/repos",
      "events_url": "https://api.github.com/users/danlucraft/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danlucraft/received_events",
      "type": "User",
      "site_admin": false,
      "score": 28.468105
    },
    {
      "login": "DanielTomlinson",
      "id": 1330683,
      "avatar_url": "https://avatars.githubusercontent.com/u/1330683?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DanielTomlinson",
      "html_url": "https://github.com/DanielTomlinson",
      "followers_url": "https://api.github.com/users/DanielTomlinson/followers",
      "following_url": "https://api.github.com/users/DanielTomlinson/following{/other_user}",
      "gists_url": "https://api.github.com/users/DanielTomlinson/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DanielTomlinson/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DanielTomlinson/subscriptions",
      "organizations_url": "https://api.github.com/users/DanielTomlinson/orgs",
      "repos_url": "https://api.github.com/users/DanielTomlinson/repos",
      "events_url": "https://api.github.com/users/DanielTomlinson/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DanielTomlinson/received_events",
      "type": "User",
      "site_admin": false,
      "score": 28.468105
    },
    {
      "login": "danzeeeman",
      "id": 719564,
      "avatar_url": "https://avatars.githubusercontent.com/u/719564?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danzeeeman",
      "html_url": "https://github.com/danzeeeman",
      "followers_url": "https://api.github.com/users/danzeeeman/followers",
      "following_url": "https://api.github.com/users/danzeeeman/following{/other_user}",
      "gists_url": "https://api.github.com/users/danzeeeman/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danzeeeman/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danzeeeman/subscriptions",
      "organizations_url": "https://api.github.com/users/danzeeeman/orgs",
      "repos_url": "https://api.github.com/users/danzeeeman/repos",
      "events_url": "https://api.github.com/users/danzeeeman/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danzeeeman/received_events",
      "type": "User",
      "site_admin": false,
      "score": 28.468105
    },
    {
      "login": "gaearon",
      "id": 810438,
      "avatar_url": "https://avatars.githubusercontent.com/u/810438?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gaearon",
      "html_url": "https://github.com/gaearon",
      "followers_url": "https://api.github.com/users/gaearon/followers",
      "following_url": "https://api.github.com/users/gaearon/following{/other_user}",
      "gists_url": "https://api.github.com/users/gaearon/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gaearon/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gaearon/subscriptions",
      "organizations_url": "https://api.github.com/users/gaearon/orgs",
      "repos_url": "https://api.github.com/users/gaearon/repos",
      "events_url": "https://api.github.com/users/gaearon/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gaearon/received_events",
      "type": "User",
      "site_admin": false,
      "score": 28.468105
    },
    {
      "login": "danielgtaylor",
      "id": 106826,
      "avatar_url": "https://avatars.githubusercontent.com/u/106826?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielgtaylor",
      "html_url": "https://github.com/danielgtaylor",
      "followers_url": "https://api.github.com/users/danielgtaylor/followers",
      "following_url": "https://api.github.com/users/danielgtaylor/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielgtaylor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielgtaylor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielgtaylor/subscriptions",
      "organizations_url": "https://api.github.com/users/danielgtaylor/orgs",
      "repos_url": "https://api.github.com/users/danielgtaylor/repos",
      "events_url": "https://api.github.com/users/danielgtaylor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielgtaylor/received_events",
      "type": "User",
      "site_admin": false,
      "score": 26.167
    },
    {
      "login": "dmotz",
      "id": 302080,
      "avatar_url": "https://avatars.githubusercontent.com/u/302080?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dmotz",
      "html_url": "https://github.com/dmotz",
      "followers_url": "https://api.github.com/users/dmotz/followers",
      "following_url": "https://api.github.com/users/dmotz/following{/other_user}",
      "gists_url": "https://api.github.com/users/dmotz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dmotz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dmotz/subscriptions",
      "organizations_url": "https://api.github.com/users/dmotz/orgs",
      "repos_url": "https://api.github.com/users/dmotz/repos",
      "events_url": "https://api.github.com/users/dmotz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dmotz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 26.167
    },
    {
      "login": "dmgarland",
      "id": 133712,
      "avatar_url": "https://avatars.githubusercontent.com/u/133712?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dmgarland",
      "html_url": "https://github.com/dmgarland",
      "followers_url": "https://api.github.com/users/dmgarland/followers",
      "following_url": "https://api.github.com/users/dmgarland/following{/other_user}",
      "gists_url": "https://api.github.com/users/dmgarland/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dmgarland/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dmgarland/subscriptions",
      "organizations_url": "https://api.github.com/users/dmgarland/orgs",
      "repos_url": "https://api.github.com/users/dmgarland/repos",
      "events_url": "https://api.github.com/users/dmgarland/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dmgarland/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.790255
    },
    {
      "login": "danro",
      "id": 393520,
      "avatar_url": "https://avatars.githubusercontent.com/u/393520?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danro",
      "html_url": "https://github.com/danro",
      "followers_url": "https://api.github.com/users/danro/followers",
      "following_url": "https://api.github.com/users/danro/following{/other_user}",
      "gists_url": "https://api.github.com/users/danro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danro/subscriptions",
      "organizations_url": "https://api.github.com/users/danro/orgs",
      "repos_url": "https://api.github.com/users/danro/repos",
      "events_url": "https://api.github.com/users/danro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danro/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.401234
    },
    {
      "login": "dbs",
      "id": 317113,
      "avatar_url": "https://avatars.githubusercontent.com/u/317113?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dbs",
      "html_url": "https://github.com/dbs",
      "followers_url": "https://api.github.com/users/dbs/followers",
      "following_url": "https://api.github.com/users/dbs/following{/other_user}",
      "gists_url": "https://api.github.com/users/dbs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dbs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dbs/subscriptions",
      "organizations_url": "https://api.github.com/users/dbs/orgs",
      "repos_url": "https://api.github.com/users/dbs/repos",
      "events_url": "https://api.github.com/users/dbs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dbs/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.401234
    },
    {
      "login": "DanielVartanov",
      "id": 21388,
      "avatar_url": "https://avatars.githubusercontent.com/u/21388?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DanielVartanov",
      "html_url": "https://github.com/DanielVartanov",
      "followers_url": "https://api.github.com/users/DanielVartanov/followers",
      "following_url": "https://api.github.com/users/DanielVartanov/following{/other_user}",
      "gists_url": "https://api.github.com/users/DanielVartanov/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DanielVartanov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DanielVartanov/subscriptions",
      "organizations_url": "https://api.github.com/users/DanielVartanov/orgs",
      "repos_url": "https://api.github.com/users/DanielVartanov/repos",
      "events_url": "https://api.github.com/users/DanielVartanov/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DanielVartanov/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.401234
    },
    {
      "login": "dangrossman",
      "id": 407706,
      "avatar_url": "https://avatars.githubusercontent.com/u/407706?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dangrossman",
      "html_url": "https://github.com/dangrossman",
      "followers_url": "https://api.github.com/users/dangrossman/followers",
      "following_url": "https://api.github.com/users/dangrossman/following{/other_user}",
      "gists_url": "https://api.github.com/users/dangrossman/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dangrossman/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dangrossman/subscriptions",
      "organizations_url": "https://api.github.com/users/dangrossman/orgs",
      "repos_url": "https://api.github.com/users/dangrossman/repos",
      "events_url": "https://api.github.com/users/dangrossman/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dangrossman/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.401234
    },
    {
      "login": "dpup",
      "id": 206453,
      "avatar_url": "https://avatars.githubusercontent.com/u/206453?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dpup",
      "html_url": "https://github.com/dpup",
      "followers_url": "https://api.github.com/users/dpup/followers",
      "following_url": "https://api.github.com/users/dpup/following{/other_user}",
      "gists_url": "https://api.github.com/users/dpup/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dpup/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dpup/subscriptions",
      "organizations_url": "https://api.github.com/users/dpup/orgs",
      "repos_url": "https://api.github.com/users/dpup/repos",
      "events_url": "https://api.github.com/users/dpup/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dpup/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.401234
    },
    {
      "login": "damelang",
      "id": 20817,
      "avatar_url": "https://avatars.githubusercontent.com/u/20817?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/damelang",
      "html_url": "https://github.com/damelang",
      "followers_url": "https://api.github.com/users/damelang/followers",
      "following_url": "https://api.github.com/users/damelang/following{/other_user}",
      "gists_url": "https://api.github.com/users/damelang/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/damelang/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/damelang/subscriptions",
      "organizations_url": "https://api.github.com/users/damelang/orgs",
      "repos_url": "https://api.github.com/users/damelang/repos",
      "events_url": "https://api.github.com/users/damelang/events{/privacy}",
      "received_events_url": "https://api.github.com/users/damelang/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.401234
    },
    {
      "login": "dazld",
      "id": 201036,
      "avatar_url": "https://avatars.githubusercontent.com/u/201036?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dazld",
      "html_url": "https://github.com/dazld",
      "followers_url": "https://api.github.com/users/dazld/followers",
      "following_url": "https://api.github.com/users/dazld/following{/other_user}",
      "gists_url": "https://api.github.com/users/dazld/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dazld/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dazld/subscriptions",
      "organizations_url": "https://api.github.com/users/dazld/orgs",
      "repos_url": "https://api.github.com/users/dazld/repos",
      "events_url": "https://api.github.com/users/dazld/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dazld/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.401234
    },
    {
      "login": "danopia",
      "id": 40628,
      "avatar_url": "https://avatars.githubusercontent.com/u/40628?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danopia",
      "html_url": "https://github.com/danopia",
      "followers_url": "https://api.github.com/users/danopia/followers",
      "following_url": "https://api.github.com/users/danopia/following{/other_user}",
      "gists_url": "https://api.github.com/users/danopia/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danopia/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danopia/subscriptions",
      "organizations_url": "https://api.github.com/users/danopia/orgs",
      "repos_url": "https://api.github.com/users/danopia/repos",
      "events_url": "https://api.github.com/users/danopia/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danopia/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.401234
    },
    {
      "login": "dnewcome",
      "id": 160722,
      "avatar_url": "https://avatars.githubusercontent.com/u/160722?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dnewcome",
      "html_url": "https://github.com/dnewcome",
      "followers_url": "https://api.github.com/users/dnewcome/followers",
      "following_url": "https://api.github.com/users/dnewcome/following{/other_user}",
      "gists_url": "https://api.github.com/users/dnewcome/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dnewcome/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dnewcome/subscriptions",
      "organizations_url": "https://api.github.com/users/dnewcome/orgs",
      "repos_url": "https://api.github.com/users/dnewcome/repos",
      "events_url": "https://api.github.com/users/dnewcome/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dnewcome/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.401234
    },
    {
      "login": "danpalmer",
      "id": 202400,
      "avatar_url": "https://avatars.githubusercontent.com/u/202400?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danpalmer",
      "html_url": "https://github.com/danpalmer",
      "followers_url": "https://api.github.com/users/danpalmer/followers",
      "following_url": "https://api.github.com/users/danpalmer/following{/other_user}",
      "gists_url": "https://api.github.com/users/danpalmer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danpalmer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danpalmer/subscriptions",
      "organizations_url": "https://api.github.com/users/danpalmer/orgs",
      "repos_url": "https://api.github.com/users/danpalmer/repos",
      "events_url": "https://api.github.com/users/danpalmer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danpalmer/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.401234
    },
    {
      "login": "danmayer",
      "id": 24925,
      "avatar_url": "https://avatars.githubusercontent.com/u/24925?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danmayer",
      "html_url": "https://github.com/danmayer",
      "followers_url": "https://api.github.com/users/danmayer/followers",
      "following_url": "https://api.github.com/users/danmayer/following{/other_user}",
      "gists_url": "https://api.github.com/users/danmayer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danmayer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danmayer/subscriptions",
      "organizations_url": "https://api.github.com/users/danmayer/orgs",
      "repos_url": "https://api.github.com/users/danmayer/repos",
      "events_url": "https://api.github.com/users/danmayer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danmayer/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.401234
    },
    {
      "login": "schlosser",
      "id": 2433509,
      "avatar_url": "https://avatars.githubusercontent.com/u/2433509?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/schlosser",
      "html_url": "https://github.com/schlosser",
      "followers_url": "https://api.github.com/users/schlosser/followers",
      "following_url": "https://api.github.com/users/schlosser/following{/other_user}",
      "gists_url": "https://api.github.com/users/schlosser/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/schlosser/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/schlosser/subscriptions",
      "organizations_url": "https://api.github.com/users/schlosser/orgs",
      "repos_url": "https://api.github.com/users/schlosser/repos",
      "events_url": "https://api.github.com/users/schlosser/events{/privacy}",
      "received_events_url": "https://api.github.com/users/schlosser/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.401234
    },
    {
      "login": "danjenkins",
      "id": 243117,
      "avatar_url": "https://avatars.githubusercontent.com/u/243117?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danjenkins",
      "html_url": "https://github.com/danjenkins",
      "followers_url": "https://api.github.com/users/danjenkins/followers",
      "following_url": "https://api.github.com/users/danjenkins/following{/other_user}",
      "gists_url": "https://api.github.com/users/danjenkins/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danjenkins/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danjenkins/subscriptions",
      "organizations_url": "https://api.github.com/users/danjenkins/orgs",
      "repos_url": "https://api.github.com/users/danjenkins/repos",
      "events_url": "https://api.github.com/users/danjenkins/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danjenkins/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.401234
    },
    {
      "login": "daneden",
      "id": 439365,
      "avatar_url": "https://avatars.githubusercontent.com/u/439365?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/daneden",
      "html_url": "https://github.com/daneden",
      "followers_url": "https://api.github.com/users/daneden/followers",
      "following_url": "https://api.github.com/users/daneden/following{/other_user}",
      "gists_url": "https://api.github.com/users/daneden/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/daneden/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/daneden/subscriptions",
      "organizations_url": "https://api.github.com/users/daneden/orgs",
      "repos_url": "https://api.github.com/users/daneden/repos",
      "events_url": "https://api.github.com/users/daneden/events{/privacy}",
      "received_events_url": "https://api.github.com/users/daneden/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.401234
    },
    {
      "login": "flyswatter",
      "id": 542863,
      "avatar_url": "https://avatars.githubusercontent.com/u/542863?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flyswatter",
      "html_url": "https://github.com/flyswatter",
      "followers_url": "https://api.github.com/users/flyswatter/followers",
      "following_url": "https://api.github.com/users/flyswatter/following{/other_user}",
      "gists_url": "https://api.github.com/users/flyswatter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flyswatter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flyswatter/subscriptions",
      "organizations_url": "https://api.github.com/users/flyswatter/orgs",
      "repos_url": "https://api.github.com/users/flyswatter/repos",
      "events_url": "https://api.github.com/users/flyswatter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flyswatter/received_events",
      "type": "User",
      "site_admin": false,
      "score": 24.401234
    },
    {
      "login": "danielsdeleo",
      "id": 37162,
      "avatar_url": "https://avatars.githubusercontent.com/u/37162?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielsdeleo",
      "html_url": "https://github.com/danielsdeleo",
      "followers_url": "https://api.github.com/users/danielsdeleo/followers",
      "following_url": "https://api.github.com/users/danielsdeleo/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielsdeleo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielsdeleo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielsdeleo/subscriptions",
      "organizations_url": "https://api.github.com/users/danielsdeleo/orgs",
      "repos_url": "https://api.github.com/users/danielsdeleo/repos",
      "events_url": "https://api.github.com/users/danielsdeleo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielsdeleo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 22.428858
    },
    {
      "login": "danprince",
      "id": 1266011,
      "avatar_url": "https://avatars.githubusercontent.com/u/1266011?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danprince",
      "html_url": "https://github.com/danprince",
      "followers_url": "https://api.github.com/users/danprince/followers",
      "following_url": "https://api.github.com/users/danprince/following{/other_user}",
      "gists_url": "https://api.github.com/users/danprince/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danprince/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danprince/subscriptions",
      "organizations_url": "https://api.github.com/users/danprince/orgs",
      "repos_url": "https://api.github.com/users/danprince/repos",
      "events_url": "https://api.github.com/users/danprince/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danprince/received_events",
      "type": "User",
      "site_admin": false,
      "score": 22.428858
    },
    {
      "login": "dphiffer",
      "id": 38114,
      "avatar_url": "https://avatars.githubusercontent.com/u/38114?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dphiffer",
      "html_url": "https://github.com/dphiffer",
      "followers_url": "https://api.github.com/users/dphiffer/followers",
      "following_url": "https://api.github.com/users/dphiffer/following{/other_user}",
      "gists_url": "https://api.github.com/users/dphiffer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dphiffer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dphiffer/subscriptions",
      "organizations_url": "https://api.github.com/users/dphiffer/orgs",
      "repos_url": "https://api.github.com/users/dphiffer/repos",
      "events_url": "https://api.github.com/users/dphiffer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dphiffer/received_events",
      "type": "User",
      "site_admin": false,
      "score": 22.428858
    },
    {
      "login": "dangrover",
      "id": 96156,
      "avatar_url": "https://avatars.githubusercontent.com/u/96156?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dangrover",
      "html_url": "https://github.com/dangrover",
      "followers_url": "https://api.github.com/users/dangrover/followers",
      "following_url": "https://api.github.com/users/dangrover/following{/other_user}",
      "gists_url": "https://api.github.com/users/dangrover/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dangrover/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dangrover/subscriptions",
      "organizations_url": "https://api.github.com/users/dangrover/orgs",
      "repos_url": "https://api.github.com/users/dangrover/repos",
      "events_url": "https://api.github.com/users/dangrover/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dangrover/received_events",
      "type": "User",
      "site_admin": false,
      "score": 22.428858
    },
    {
      "login": "danhively",
      "id": 971699,
      "avatar_url": "https://avatars.githubusercontent.com/u/971699?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danhively",
      "html_url": "https://github.com/danhively",
      "followers_url": "https://api.github.com/users/danhively/followers",
      "following_url": "https://api.github.com/users/danhively/following{/other_user}",
      "gists_url": "https://api.github.com/users/danhively/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danhively/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danhively/subscriptions",
      "organizations_url": "https://api.github.com/users/danhively/orgs",
      "repos_url": "https://api.github.com/users/danhively/repos",
      "events_url": "https://api.github.com/users/danhively/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danhively/received_events",
      "type": "User",
      "site_admin": false,
      "score": 22.428858
    },
    {
      "login": "danclien",
      "id": 764962,
      "avatar_url": "https://avatars.githubusercontent.com/u/764962?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danclien",
      "html_url": "https://github.com/danclien",
      "followers_url": "https://api.github.com/users/danclien/followers",
      "following_url": "https://api.github.com/users/danclien/following{/other_user}",
      "gists_url": "https://api.github.com/users/danclien/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danclien/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danclien/subscriptions",
      "organizations_url": "https://api.github.com/users/danclien/orgs",
      "repos_url": "https://api.github.com/users/danclien/repos",
      "events_url": "https://api.github.com/users/danclien/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danclien/received_events",
      "type": "User",
      "site_admin": false,
      "score": 20.33436
    }
  ]
export default stub
